/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_parameter (XDR *xdrs, parameter *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->y, ~0))
		 return FALSE;
	return TRUE;
}
