/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_proc3_1_argument (XDR *xdrs, proc3_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->y, ~0))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
