#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "msg.h"

/*
 * Declare the server-side function prototypes for the remote
 * procedures. These prototypes are generated by RPCGen.
 */
int *proc1_1_svc(int *argp, struct svc_req *rqstp)
{
    static int result;
    printf("Received request for procedure 1 with argument %d\n", *argp);
    result = *argp + 1; // Perform some operation on the argument
    return &result;
}

/*
 * Define the procedure 2 prototype. It accepts an integer and
 * returns a floating point.
 */
float *proc2_1_svc(int *argp, struct svc_req *rqstp)
{
    static float result;
    printf("Received request for procedure 2 with argument %d\n", *argp);
    result = (float)*argp / 2; // Perform some operation on the argument
    return &result;
}

/*
 * Define the procedure 3 prototype. It accepts an integer by
 * reference and returns a string.
 */
char **proc3_1_svc(int *argp, struct svc_req *rqstp)
{
    static char result[16];
    printf("Received request for procedure 3 with argument %d\n", *argp);
    sprintf(result, "Result: %d", *argp * 3); // Perform some operation on the argument
    return &result;
}
